id: A7A92DC0C
title: 'Cloud Banks of Blessings: A Brief Prayer to the Garland of Successive Rebirths'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:30:17.863473
  last_modified_at: 2022-03-01 01:30:17.863475
