id: A7A92DC0C
title: 'The Profound Path of Guru Yoga: A Way to Freedom for the Fortunate'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:30:17.868006
  last_modified_at: 2022-03-01 01:30:17.868009
