id: A7A92DC0C
title: 'The Hook of Compassion: A Prayer to the Garland of Successive Rebirths'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:30:17.865693
  last_modified_at: 2022-03-01 01:30:17.865696
