id: A7A92DC0C
title: A Brief Prayer to Sera Khandro
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:30:17.857583
  last_modified_at: 2022-03-01 01:30:17.857591
