id: A7A92DC0C
title: Guru Yoga
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:30:17.864762
  last_modified_at: 2022-03-01 01:30:17.864766
