id: A7A92DC0C
title: 'Burgeoning Benefit and Happiness: An Aspiration to be Reborn in the Land of
  Turquoise Leaves'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:30:17.862051
  last_modified_at: 2022-03-01 01:30:17.862053
