id: A7A92DC0C
title: A Supplication to Noble Tārā, The Wish-Fulfilling Cornucopia
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:30:17.860385
  last_modified_at: 2022-03-01 01:30:17.860388
